=begin pod

=head1 NAME

B<SantaClaus::Utils> - Provides Raku software tools for Santa Claus and his Elves

=head1 SYNOPSIS

=begin code :lang<raku>

use SantaClaus::Utils;

add-entry;     # adds a journal entry template to the
               # user's '$HOME/journal' text file
check-journal; # checks the journal file for correct syntax
=end code

=head1 DESCRIPTION

The Raku module B<SantaClaus::Utils> is used by Santa's staff to
create and manage individual task journal entries. It also provide
tools to manage as the entire collection of task journals for all
Santa's helpers to provide status reports and other reports for Santa
and his staff.

=head1 AUTHOR

Tom Browder <tbrowder@acm.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2021 Tom Browder

This library is free software; you may redistribute it or modify it under the Artistic License 2.0.

=end pod
